# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration.html

scale_factor = 1.25
theme = "Catppuccin Latte"

[servers.liberachat]
nickname = "nejni"
server = "irc.libera.chat"
channels = ["#sway", "#archlinux", "#archlinux-offtopic", "#linux"]
alt_nicks = ["nejni_", "nejni__", "nejni-marji", "nejni-marji_"]

[servers.liberachat.sasl.plain]
username = "nejni-marji"
password_file = "~/Dotfiles/extras/secrets/halloy"

[font]
family = "Comic Code"
size = 14

[actions.buffer]
click_channel_name = "replace-pane"
click_highlight = "replace-pane"
click_username = "replace-pane"
local = "replace-pane"
message_channel = "replace-pane"
message_user = "replace-pane"

[actions.sidebar]
buffer = "replace-pane"

[sidebar]
max_width = 125

[buffer.channel.nicklist]
enabled = false

[buffer.nickname]
alignment = "right"
brackets = { left = "<", right = ">" }
truncate = 10

[notifications.highlight]
sound = "bloop"
show_toast = true
show_content = true
request_attention = false

[notifications.direct_message]
sound = "peck"
show_toast = true
show_content = true
request_attention = false
